name: validate_template_inputs

on:
  workflow_call:
    inputs:
      template_repo:
        description: 'URL of the cookiecutter template repo'
        required: true
        type: string
      repo_branch:
        description: 'Branch of the project repo to update'
        required: true
        type: string
      update_workflow_ref:
        description: 'Ref for update workflow (e.g., main or a commit SHA)'
        required: false
        default: 'main'
        type: string

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch all remote branches
        run: git fetch origin '+refs/heads/*:refs/remotes/origin/*'

      - name: Validate repo_branch exists
        run: |
          if ! git show-ref --verify --quiet "refs/remotes/origin/${{ inputs.repo_branch }}"; then
            echo "::error ::Branch '${{ inputs.repo_branch }}' not found!"
            exit 1
          fi
          
  dispatch-update:
    needs: validate
    uses: ./.github/workflows/template_update.yml
    with:
      template_repo: ${{ inputs.template_repo }}
      repo_branch: ${{ inputs.repo_branch }}
